FROM multiverseframework/multiverse-tutorials:ubuntu-20.04@sha256:2cdf9a11c12062bb025d47e3faef5e0c641116c37d22def353c5d4128680107a

USER root
ENV SHELL=/bin/bash

# Create non-root user jovyan
ENV NB_USER=jovyan
ENV NB_UID=1000
ENV USER ${NB_USER}
ENV NB_UID ${NB_UID}
ENV HOME /home/${NB_USER}
# RUN adduser --disabled-password \
#     --gecos "Default user" \
#     --uid ${NB_UID} \
#     ${NB_USER}

# Install apt packages
RUN apt-get update && apt-get install -y curl vim xvfb htop
# Install nodejs (dependency of Jupyterlab extensions)
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash - &&\
    apt-get install -y nodejs

# Install jupyterlab and related python packages
RUN pip install pip --upgrade
RUN pip install "cython<3.0.0" wheel
RUN pip install pyyaml==5.4.1 --no-build-isolation
RUN pip install --no-cache-dir --ignore-installed notebook==6.4.12 jupyterlab==3.6.5 \
    wstool pyOpenSSL==23.2.0 cryptography==38.0.4 \
    jupyter-resource-usage jupyter-offlinenotebook \
    jupyter-server-proxy jupyterlab-git jlab-enhanced-cell-toolbar \
    autobahn gnupg twisted cbor2 empy ipywidgets  \
    pymongo Pillow pycryptodomex simplejpeg tqdm \
    https://raw.githubusercontent.com/yxzhan/jupyterlab-rviz/master/dist/jupyterlab_rviz-0.3.1.tar.gz \
    empy==3.3.4

# Allow user ${NB_USER} write some directories
RUN chown -R ${NB_UID} /home/Multiverse
RUN chown -R ${NB_UID} /home/Multiverse-Tutorials

# Copy necessary files
COPY --chown=${NB_USER}:users binder /home/binder

RUN chown -R ${NB_UID} /home/${NB_USER} && chown ${NB_UID} /home/Multiverse
USER ${NB_USER}

# Install OH-My-Bash
RUN bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)" --unattended && \
    sed -i 's/OSH_THEME="font"/OSH_THEME="half-life"/' /home/${NB_USER}/.bashrc
COPY --chown=${NB_USER}:users binder/jupyter-settings.json /usr/local/share/jupyter/lab/settings/overrides.json

WORKDIR /home
ENTRYPOINT ["/home/binder/entrypoint.sh"]
