services:
  binderhub:
    tty: true
    image: multiverseframework/binder:ubuntu-20.04
    build:
      context: ../
      dockerfile: ./binder/Dockerfile
    container_name: multiverse-binder-container
    command: jupyter lab --allow-root --NotebookApp.token='' --no-browser --ip=0.0.0.0
    ports:
      - 8888:8888